Added support to merge analysed samples
imgag/megSAP pull request #94
Opened 2021-06-17 12:32 UTC by leonschuetz

src/Tools/merge_samples.php: also support merging of already analyzed samples

2021-06-17 13:21 UTC, marc-sturm requested changes

2021-06-17 13:21 UTC, marc-sturm commented on src/Tools/merge_samples.php
> +	exec2("mv $folder1 $backup_folder/");
Im if und else Block gleich > nach if-else verschieben

2021-06-17 13:21 UTC, marc-sturm commented on src/Tools/merge_samples.php
> +	exec2("mv $folder1 $backup_folder/");
Im if und else Block gleich > nach if-else verschieben

2021-06-17 13:21 UTC, marc-sturm commented on src/Tools/merge_samples.php
> -exec2("mv $folder1 $backup_folder/");
Im if und else Block gleich > nach if-else verschieben

2021-06-18 04:48 UTC, leonschuetz commented on src/Tools/merge_samples.php
> +	exec2("mv $folder1 $backup_folder/");
fixed

2021-06-18 04:48 UTC, leonschuetz commented on src/Tools/merge_samples.php
> +	exec2("mv $folder1 $backup_folder/");
fixed

2021-06-18 04:49 UTC, leonschuetz commented on src/Tools/merge_samples.php
> -exec2("mv $folder1 $backup_folder/");
fixed

2021-06-18 05:03 UTC, marc-sturm approved these changes

2021-06-18 05:05 UTC, merged